name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard/Pretendard-Black.otf
          weight: 900
        - asset: asset/font/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: asset/font/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: asset/font/Pretendard/Pretendard-Semibold.otf
          weight: 600
        - asset: asset/font/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: asset/font/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: asset/font/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: asset/font/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: asset/font/Pretendard/Pretendard-Thin.otf
          weight: 100

